---
title: Booleaanse operatoren in Python voorwaarden
hero_image: images/banner.png
description: Booleaanse operatoren gebruiken in if-instructies
original_url:
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: python
site_areas:
steps:
  - 
    title: Booleans in voorwaardelijke selectie

