title: Boolean operators in Python conditionals
hero_image: images/banner.png
description: Using boolean operators in if, elif statements
original_url:
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 # possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: false
curriculum: 
interests: 
technologies: python
site_areas:
steps:
  - title: Booleans in conditional selection

