---
title: Operadores booleanos en condicionales de Python
hero_image: images/banner.png
description: Usar operadores booleanos en sentencias if
original_url:
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: python
site_areas:
steps:
  - 
    title: Booleanos en selección condicional

